# Generated by natu

import natu/[memory, oam, utils]


type
  Graphic* = enum
    gfxTestCharacter

block:
  {.compile:"./graphics.c".}

let palData {.importc:"natuGfxPalData", extern:"natuGfxPalData", codegenDecl:"extern const $# $#".}: array[15, char]
let imgData {.importc:"natuGfxImgData", extern:"natuGfxImgData", codegenDecl:"extern const $# $#".}: array[129, char]

const staticGfxData: array[Graphic, GraphicData] = [
  gfxTestCharacter: GraphicData(bpp: 4, size: s16x16, flags: {}, w: 16, h: 16, imgPos: 0, imgWords: 32, palNum: 0, palPos: 0, palHalfwords: 7, frames: 1, frameWords: 32),
]

var palUsages {.codegenDecl:EWRAM_DATA.}: array[1, uint16]

template data*(g: Graphic): GraphicData = staticGfxData[g]
template palUsage*(g: Graphic): var uint16 = palUsages[g.data.palNum]
template palDataPtr*(g: Graphic): pointer = unsafeAddr palData[g.data.palPos]
template imgDataPtr*(g: Graphic): pointer = unsafeAddr imgData[g.data.imgPos]

