/* Generated by Nim Compiler v2.0.4 */
/* Compiled for: Standalone, arm, gcc */
/* Command for C compiler:
   /usr/bin/arm-none-eabi-gcc -c -nostdinc -isystem /home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/acsl/include -mthumb -mthumb-interwork -mcpu=arm7tdmi -g -O2 -ffast-math -Wno-unused-variable -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-stringop-overflow   -I/home/afisher/.choosenim/toolchains/nim-2.0.4/lib -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/libtonc/include -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/maxmod/include -I/home/afisher/projects/gbadev/nimcache -I/home/afisher/projects/gbadev/src -o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.choosenim@stoolchains@snim-2.0.4@slib@ssystem.nim.c.o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.choosenim@stoolchains@snim-2.0.4@slib@ssystem.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimNode TNimNode;
typedef struct TNimType TNimType;
typedef struct RootObj RootObj;
typedef struct RootEffect RootEffect;
typedef struct Exception Exception;
typedef struct tySequence__W5u7dtuXI9c4BOBf9bW9bZhWQ tySequence__W5u7dtuXI9c4BOBf9bW9bZhWQ;
typedef struct TSafePoint TSafePoint;
typedef struct ForLoopStmt ForLoopStmt;
typedef struct tyObject_StackTraceEntry__6CL1lcV9bxEp7TPS0fN8sRQ tyObject_StackTraceEntry__6CL1lcV9bxEp7TPS0fN8sRQ;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimNodeKind__Y2G2pUQjr4F5Xiqu3tIq9bA;
struct TNimNode {
	tyEnum_TNimNodeKind__Y2G2pUQjr4F5Xiqu3tIq9bA kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
typedef NU8 tyEnum_TNimKind__JQqVBAuFUw8A9ajP89ctnUCw;
typedef NU8 tySet_tyEnum_TNimTypeFlag__w2BCt56S3PAfbHf8acLiVA;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__JQqVBAuFUw8A9ajP89ctnUCw kind;
	tySet_tyEnum_TNimTypeFlag__w2BCt56S3PAfbHf8acLiVA flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct RootEffect {
  RootObj Sup;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__W5u7dtuXI9c4BOBf9bW9bZhWQ* trace;
	Exception* up;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e_p0);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw) (Exception* e_p0);
struct TSafePoint {
	TSafePoint* prev;
	NI status;
	jmp_buf context;
};
struct ForLoopStmt {
	char dummy;
};
struct tyObject_StackTraceEntry__6CL1lcV9bxEp7TPS0fN8sRQ {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__W5u7dtuXI9c4BOBf9bW9bZhWQ {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__6CL1lcV9bxEp7TPS0fN8sRQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__system_u2007;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__system_u2010;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__system_u2012;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook__system_u2015;
