/* Generated by Nim Compiler v2.0.4 */
/* Compiled for: Standalone, arm, gcc */
/* Command for C compiler:
   /usr/bin/arm-none-eabi-gcc -c -nostdinc -isystem /home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/acsl/include -mthumb -mthumb-interwork -mcpu=arm7tdmi -g -O2 -ffast-math -Wno-unused-variable -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-stringop-overflow   -I/home/afisher/.choosenim/toolchains/nim-2.0.4/lib -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/libtonc/include -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/maxmod/include -I/home/afisher/projects/gbadev/nimcache -I/home/afisher/projects/gbadev/src -o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sprivate@sreg.nim.c.o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sprivate@sreg.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct DispCnt DispCnt;
typedef struct DispStat DispStat;
typedef struct BgCnt BgCnt;
typedef struct WinH WinH;
typedef struct WinV WinV;
struct DispCnt {
	NI mode:3;
	NIM_BOOL gb:1;
	NIM_BOOL page:1;
	NIM_BOOL oamHbl:1;
	NIM_BOOL obj1d:1;
	NIM_BOOL blank:1;
	NIM_BOOL bg0:1;
	NIM_BOOL bg1:1;
	NIM_BOOL bg2:1;
	NIM_BOOL bg3:1;
	NIM_BOOL obj:1;
	NIM_BOOL win0:1;
	NIM_BOOL win1:1;
	NIM_BOOL winObj:1;
	NIM_BOOL gswap:1;
	NU unused:15;
};
struct DispStat {
	NIM_BOOL inVBlank:1;
	NIM_BOOL inHBlank:1;
	NIM_BOOL inVCountTrigger:1;
	NIM_BOOL vblankIrq:1;
	NIM_BOOL hblankIrq:1;
	NIM_BOOL vcountIrq:1;
	NU16 unused:2;
	NU16 vcountTrigger:8;
};
struct BgCnt {
	NU16 prio:2;
	NU16 cbb:2;
	NU16 unused:2;
	NIM_BOOL mos:1;
	NIM_BOOL is8bpp:1;
	NU16 sbb:5;
	NIM_BOOL wrap:1;
	NU16 size:2;
};
struct WinH {
	NU8 right:8;
	NU8 left:8;
};
struct WinV {
	NU8 bottom:8;
	NU8 top:8;
};
