/* Generated by Nim Compiler v2.0.4 */
/* Compiled for: Standalone, arm, gcc */
/* Command for C compiler:
   /usr/bin/arm-none-eabi-gcc -c -nostdinc -isystem /home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/acsl/include -mthumb -mthumb-interwork -mcpu=arm7tdmi -g -O2 -ffast-math -Wno-unused-variable -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-stringop-overflow   -I/home/afisher/.choosenim/toolchains/nim-2.0.4/lib -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/libtonc/include -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/maxmod/include -I/home/afisher/projects/gbadev/nimcache -I/home/afisher/projects/gbadev/src -o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sprivate@smemmap.nim.c.o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sprivate@smemmap.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "tonc_types.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU16 tyArray__GfVb34yyvKRvN9bvme330zw[3];
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZmemmap_u439)(OBJ_ATTR* dest_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZmemmap_u469)(OBJ_AFFINE* dest_p0) {
}
