/* Generated by Nim Compiler v2.0.4 */
/* Compiled for: Standalone, arm, gcc */
/* Command for C compiler:
   /usr/bin/arm-none-eabi-gcc -c -nostdinc -isystem /home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/acsl/include -mthumb -mthumb-interwork -mcpu=arm7tdmi -g -O2 -ffast-math -Wno-unused-variable -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-stringop-overflow   -I/home/afisher/.choosenim/toolchains/nim-2.0.4/lib -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/libtonc/include -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/maxmod/include -I/home/afisher/projects/gbadev/nimcache -I/home/afisher/projects/gbadev/src -o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sirq.nim.c.o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sirq.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "tonc_core.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU16 tySet_tyEnum_IrqIndex__w9aD3LdfVvE3H0BK5MsbGew;
typedef N_NIMCALL_PTR(void, FnPtr) (void);
typedef FnPtr tyArray__8ES2Zp0nnBIR5KuYHm8RRA[14];
N_LIB_PRIVATE N_NIMCALL(void, init__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZirq_u5)(void);
N_NIMCALL(void, IRQ_GlobalInterruptHandler)(void);
N_LIB_PRIVATE tyArray__8ES2Zp0nnBIR5KuYHm8RRA IRQ_VectorTable;
N_LIB_PRIVATE N_NIMCALL(void, init__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZirq_u5)(void) {
	(*(volatile NU8*)(0x4000208)) = NIM_FALSE;
	(*(volatile NU16*)(0x4000200)) = 0;
	(*(volatile NU16*)(0x4000202)) = 16383;
	memset32(((void*) (IRQ_VectorTable)), ((NU32)0), ((NI)14));
	(*(volatile FnPtr*)(0x03FFFFFC)) = IRQ_GlobalInterruptHandler;
	(*(volatile NU8*)(0x4000208)) = NIM_TRUE;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnatuminus0dot2dot1minus389a3c9b6e3ee0c2fc5c91865455308bc2005952atsnatuatsirqdotnim_Init000)(void) {
{
	init__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZirq_u5();
}
}

