/* Generated by Nim Compiler v2.0.4 */
/* Compiled for: Standalone, arm, gcc */
/* Command for C compiler:
   /usr/bin/arm-none-eabi-gcc -c -nostdinc -isystem /home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/acsl/include -mthumb -mthumb-interwork -mcpu=arm7tdmi -g -O2 -ffast-math -Wno-unused-variable -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-stringop-overflow   -I/home/afisher/.choosenim/toolchains/nim-2.0.4/lib -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/libtonc/include -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/maxmod/include -I/home/afisher/projects/gbadev/nimcache -I/home/afisher/projects/gbadev/src -o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sprivate@spanics.nim.c.o /home/afisher/projects/gbadev/nimcache/@m..@s..@s..@s.nimble@spkgs2@snatu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952@snatu@sprivate@spanics.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include "tonc_tte.h"
#include "tonc_memmap.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct DispCnt DispCnt;
typedef struct BgCnt BgCnt;
typedef NU32 tySet_tyEnum_ResetFlag__SRSTY33ZgZKEgsLZ7LYiSQ;
struct DispCnt {
	NI mode:3;
	NIM_BOOL gb:1;
	NIM_BOOL page:1;
	NIM_BOOL oamHbl:1;
	NIM_BOOL obj1d:1;
	NIM_BOOL blank:1;
	NIM_BOOL bg0:1;
	NIM_BOOL bg1:1;
	NIM_BOOL bg2:1;
	NIM_BOOL bg3:1;
	NIM_BOOL obj:1;
	NIM_BOOL win0:1;
	NIM_BOOL win1:1;
	NIM_BOOL winObj:1;
	NIM_BOOL gswap:1;
	NU unused:15;
};
struct BgCnt {
	NU16 prio:2;
	NU16 cbb:2;
	NU16 unused:2;
	NIM_BOOL mos:1;
	NIM_BOOL is8bpp:1;
	NU16 sbb:5;
	NIM_BOOL wrap:1;
	NU16 size:2;
};
N_LIB_PRIVATE N_NIMCALL(void, natuPanic)(NCSTRING msg1_p0, NCSTRING msg2_p1) __attribute__((noreturn));
N_NIMCALL(void, RegisterRamReset)(tySet_tyEnum_ResetFlag__SRSTY33ZgZKEgsLZ7LYiSQ flags_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NU16, toBgCntU16__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZreg_u273)(BgCnt b_p0);
static N_INLINE(NU16, rgb5__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZvideo_u46)(NI red_p0, NI green_p1, NI blue_p2);
static N_INLINE(NIM_BOOL, eqeq___system_u3401)(NCSTRING x_p0, NCSTRING y_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(NU16, toBgCntU16__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZreg_u273)(BgCnt b_p0) {
	NU16 result;
	result = (NU16)0;
	result = (*((NU16*) ((&b_p0))));
	return result;
}
static N_INLINE(NU16, rgb5__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZvideo_u46)(NI red_p0, NI green_p1, NI blue_p2) {
	NU16 result;
	result = (NU16)0;
	result = ((NU16) ((NI)((NI)(red_p0 + (NI)((NU32)(green_p1) << (NU32)(((NI)5)))) + (NI)((NU32)(blue_p2) << (NU32)(((NI)10))))));
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_u3401)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (x_p0 == 0);
		if (T6_) goto LA7_;
		T6_ = (y_p1 == 0);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, natuPanic)(NCSTRING msg1_p0, NCSTRING msg2_p1) {
	DispCnt tmpX60gensym0_;
	BgCnt bgX60gensym2_;
	NU16 T1_;
	NI T2_;
	NI T3_;
	(*(volatile NU8*)(0x4000208)) = NIM_FALSE;
	RegisterRamReset(200);
	nimZeroMem((void*)(&tmpX60gensym0_), sizeof(DispCnt));
	tmpX60gensym0_.bg0 = NIM_TRUE;
	(*(volatile DispCnt*)(0x04000000)) = tmpX60gensym0_;
	nimZeroMem((void*)(&bgX60gensym2_), sizeof(BgCnt));
	bgX60gensym2_.cbb = ((NU16)0);
	bgX60gensym2_.sbb = ((NU16)31);
	T1_ = (NU16)0;
	T1_ = toBgCntU16__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZreg_u273(bgX60gensym2_);
	tte_init_chr4c(((NI)0), T1_, ((NU16)61440), ((NU32)513), ((NU32)35587071), (&verdana9Font), NIM_NIL);
	pal_bg_mem[(((NI)0))- 0] = rgb5__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZvideo_u46(((NI)0), ((NI)0), ((NI)4));
	tte_set_pos(((NI)8), ((NI)8));
	tte_set_margins(((NI)8), ((NI)8), ((NI)232), ((NI)152));
	T2_ = (NI)0;
	T2_ = tte_write("AN ERROR OCCURRED:\012\012");
	T3_ = (NI)0;
	T3_ = tte_write(msg1_p0);
	{
		NIM_BOOL T6_;
		NI T9_;
		T6_ = (NIM_BOOL)0;
		T6_ = eqeq___system_u3401(msg2_p1, ((NCSTRING) NIM_NIL));
		if (!!(T6_)) goto LA7_;
		T9_ = (NI)0;
		T9_ = tte_write(msg2_p1);
	}
LA7_: ;
	{
		while (1) {
			__asm__("nop\n"
);
		}
	}
}
