/* Generated by Nim Compiler v2.0.4 */
/* Compiled for: Standalone, arm, gcc */
/* Command for C compiler:
   /usr/bin/arm-none-eabi-gcc -c -nostdinc -isystem /home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/acsl/include -mthumb -mthumb-interwork -mcpu=arm7tdmi -g -O2 -ffast-math -Wno-unused-variable -Wno-unused-but-set-variable -Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-stringop-overflow   -I/home/afisher/.choosenim/toolchains/nim-2.0.4/lib -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/libtonc/include -I/home/afisher/.nimble/pkgs2/natu-0.2.1-389a3c9b6e3ee0c2fc5c91865455308bc2005952/vendor/maxmod/include -I/home/afisher/projects/gbadev/nimcache -I/home/afisher/projects/gbadev/src -o /home/afisher/projects/gbadev/nimcache/@minit.nim.c.o /home/afisher/projects/gbadev/nimcache/@minit.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "tonc_tte.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct BgCnt BgCnt;
struct BgCnt {
	NU16 prio:2;
	NU16 cbb:2;
	NU16 unused:2;
	NIM_BOOL mos:1;
	NIM_BOOL is8bpp:1;
	NU16 sbb:5;
	NIM_BOOL wrap:1;
	NU16 size:2;
};
static N_INLINE(NU16, toBgCntU16__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZreg_u273)(BgCnt b_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NU16, toBgCntU16__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZreg_u273)(BgCnt b_p0) {
	NU16 result;
	result = (NU16)0;
	result = (*((NU16*) ((&b_p0))));
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, initTte__init_u4)(void) {
	BgCnt bgX60gensym0_;
	NU16 T1_;
	nimZeroMem((void*)(&bgX60gensym0_), sizeof(BgCnt));
	bgX60gensym0_.cbb = ((NU16)0);
	bgX60gensym0_.sbb = ((NU16)31);
	T1_ = (NU16)0;
	T1_ = toBgCntU16__OOZOOZOOZOnimbleZpkgs50Znatu4548O50O4945515657a51c57b54e51ee48c50fc53c5749565453525353514856bc50484853575350ZnatuZprivateZreg_u273(bgX60gensym0_);
	tte_init_chr4c(((NI)0), T1_, ((NU16)61440), ((NU32)513), ((NU32)35587071), (&verdana9Font), NIM_NIL);
	tte_set_pos(((NI)92), ((NI)68));
}
